# Generated by Django 4.1.2 on 2022-10-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_management',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
