# Generated by Django 4.1.2 on 2022-10-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='is_frontend',
            field=models.BooleanField(default=True),
        ),
    ]
