# Generated by Django 4.1.2 on 2022-12-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_userlog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlog',
            name='redirect_to',
        ),
        migrations.AddField(
            model_name='userlog',
            name='ip_address',
            field=models.CharField(default=None, editable=False, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlog',
            name='user_agent',
            field=models.CharField(default=None, editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
