# Generated by Django 4.1.2 on 2022-12-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_userlog_redirect_to_userlog_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='active_domain',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
