# Generated by Django 4.1.2 on 2022-12-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_agency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlog',
            name='active_domain',
        ),
        migrations.RemoveField(
            model_name='userlog',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='userlog',
            name='social_media',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
