# Generated by Django 4.1.2 on 2023-01-02 11:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_userlog_active_domain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelList',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.CharField(max_length=255, verbose_name='desciption')),
                ('status', models.SmallIntegerField(choices=[(1, 'Default'), (2, 'Optional')], default=2)),
            ],
            options={
                'verbose_name': 'model list',
                'verbose_name_plural': 'models list',
            },
        ),
        migrations.CreateModel(
            name='ModelListSetting',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_width', models.SmallIntegerField()),
                ('image_height', models.SmallIntegerField()),
                ('model_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modellist')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.template')),
            ],
            options={
                'verbose_name': 'model list setting',
                'verbose_name_plural': 'model list settings',
            },
        ),
        migrations.AddField(
            model_name='modellist',
            name='templates',
            field=models.ManyToManyField(through='core.ModelListSetting', to='core.template'),
        ),
    ]
