# Generated by Django 4.1.2 on 2023-01-31 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_templateowner_alter_user_is_management_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_management',
        ),
        migrations.RemoveField(
            model_name='user',
            name='menu_group',
        ),
    ]
