# Generated by Django 4.1.2 on 2023-02-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_user_is_management_remove_user_menu_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_first_enter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_main_user',
        ),
        migrations.AlterField(
            model_name='service',
            name='kind',
            field=models.SmallIntegerField(choices=[(1, 'Education'), (2, 'Travel'), (3, 'Villa')]),
        ),
    ]
