# Generated by Django 4.1.2 on 2023-04-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_user_is_first_enter_remove_user_is_main_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modellistsetting',
            name='image_height',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='modellistsetting',
            name='image_width',
            field=models.SmallIntegerField(default=0),
        ),
    ]
