# Generated by Django 4.1.2 on 2023-04-09 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20230130_1141'),
        ('core', '0014_modellist_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modellist',
            name='menu',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menu'),
        ),
    ]
