# Generated by Django 4.1.2 on 2023-04-30 12:37

from django.db import migrations, models
import uuid

def create_uuid(apps, schema_editor):
    User = apps.get_model('core', 'User')
    for user in User.objects.all():
        user.uuid = uuid.uuid4()
        user.save(update_fields=['uuid'])
        

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_user_email_confirmed_alter_service_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
            # default=uuid.uuid4, editable=False, 
            # field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(unique=True, editable=False, default=uuid.uuid4)
        )   
    ]
