# Generated by Django 4.1.2 on 2023-05-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_photo_content_type_alter_photo_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file_path',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
