# Generated by Django 4.1.2 on 2023-05-21 08:42

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_service_template_service_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='template',
        ),
        migrations.AddField(
            model_name='template',
            name='service_option',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Education'), (2, 'Travel'), (3, 'Villa'), (4, 'Corporate')], default=None, max_length=3),
            preserve_default=False,
        ),
    ]
