# Generated by Django 4.1.2 on 2023-05-21 09:05

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_service_template_template_service_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='service_option',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Education'), (2, 'Travel'), (3, 'Villa'), (4, 'Corporate')], max_length=255),
        ),
    ]
