# Generated by Django 4.1.2 on 2023-05-24 08:52

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('core', '0026_alter_template_service_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_demo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='kind',
            field=models.SmallIntegerField(choices=[(1, 'edu'), (2, 'travel'), (3, 'villa'), (4, 'corp')]),
        ),
        migrations.AlterField(
            model_name='service',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sites.site'),
        ),
        migrations.AlterField(
            model_name='template',
            name='service_option',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'edu'), (2, 'travel'), (3, 'villa'), (4, 'corp')], max_length=255),
        ),
    ]
