# Generated by Django 4.1.2 on 2023-05-26 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('core', '0027_service_is_demo_alter_service_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='site',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sites.site'),
        ),
    ]
