# Generated by Django 4.1.2 on 2023-06-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_service_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
