# Generated by Django 4.1.2 on 2023-06-15 13:34

from django.db import migrations
from core.auto_insert_core_data import create_core_data

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_agency_is_default_service_is_default'),
    ]

    operations = [
        migrations.RunPython(create_core_data)
    ]
