# Generated by Django 4.1.2 on 2023-06-16 12:19

from django.db import migrations
from core.auto_insert_core_data import create_core_data

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_update_core_data'),
    ]

    operations = [
        migrations.RunPython(auto_insert_core_data) 
    ]
