# Generated by Django 4.1.2 on 2023-06-17 02:21

from django.db import migrations
from core.auto_insert_core_data import create_core_data

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_complete_menu_translation'),
    ]

    operations = [
        migrations.RunPython(create_core_data) 
    ]
