# Generated by Django 4.1.2 on 2023-06-19 17:36

from django.db import migrations
from core.auto_insert_core_data import create_core_data

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20230617_0221'),
    ]

    operations = [
        migrations.RunPython(create_core_data) 
    ]
