# Generated by Django 4.1.2 on 2023-07-25 17:07

from django.db import migrations
from core.auto_insert_core_data import create_core_data

class Migration(migrations.Migration):

    dependencies = [
	('core', '0033_auto_20230619_1736'),
    ]

    operations = [
	migrations.RunPython(auto_insert_core_data) 
    ]
