# Generated by Django 4.1.2 on 2022-10-28 23:36

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='slug',
        ),
        migrations.CreateModel(
            name='TagsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=50, verbose_name='tags name')),
                ('slug', models.SlugField(blank=True, default='', editable=False, unique=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='education.tags')),
            ],
            options={
                'verbose_name': 'tag Translation',
                'db_table': 'education_tags_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            # bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
    ]
