# Generated by Django 4.1.2 on 2022-10-29 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_remove_tags_name_remove_tags_slug_tagstranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popuptranslation',
            name='slug',
        ),
    ]
