# Generated by Django 4.1.2 on 2022-11-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_remove_slideshow_link_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='hits',
            field=models.IntegerField(blank=True, default=0, editable=False, verbose_name='hits'),
        ),
    ]
