# Generated by Django 4.1.2 on 2022-12-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_categories_status_tags_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='position',
        ),
        migrations.AddField(
            model_name='banner',
            name='priority',
            field=models.SmallIntegerField(choices=[(1, 'High'), (2, 'Middle'), (3, 'Low')], default=3, verbose_name='priority'),
        ),
    ]
