# Generated by Django 4.1.2 on 2022-11-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_document_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='hits',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='hits'),
        ),
    ]
