# Generated by Django 4.1.2 on 2022-12-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_remove_banner_position_banner_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Draft'), (2, 'Published')], default=2),
        ),
    ]
