# Generated by Django 4.1.2 on 2022-12-01 15:42

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_alter_document_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogallery',
            name='embed_video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
