# Generated by Django 4.1.2 on 2022-11-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_tags_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcementtranslation',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='articletranslation',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='eventstranslation',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='newstranslation',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='pagestranslation',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='photogallerytranslation',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='videogallerytranslation',
            name='slug',
        ),
        migrations.AddField(
            model_name='announcement',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='events',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='videogallery',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tagstranslation',
            name='name',
            field=models.CharField(max_length=50, verbose_name='tags name'),
        ),
    ]
