# Generated by Django 4.1.2 on 2022-11-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_remove_announcementtranslation_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshow',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Draft'), (2, 'Published')], default=2),
        ),
    ]
