# Generated by Django 4.1.2 on 2022-11-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_alter_slideshow_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshow',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='link'),
        ),
    ]
