# Generated by Django 4.1.2 on 2023-04-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshowtranslation',
            name='sub_title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='sub title'),
        ),
    ]
