# Generated by Django 4.1.2 on 2023-05-13 16:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0012_howitwork_product_purchasing_cart_producttranslation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HowItWork',
            new_name='HowItWorks',
        ),
        migrations.RenameModel(
            old_name='HowItWorkTranslation',
            new_name='HowItWorksTranslation',
        ),
        migrations.AlterModelOptions(
            name='howitworkstranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'how it works Translation'},
        ),
        migrations.AlterModelTable(
            name='howitworkstranslation',
            table='education_howitworks_translation',
        ),
    ]
