# Generated by Django 4.1.2 on 2023-05-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0014_howitworks_order_item_alter_howitworks_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fasilities',
            name='order_item',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
