# Generated by Django 4.1.2 on 2023-05-16 10:51

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0016_product_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_header_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fasilities',
            name='is_header_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='howitworks',
            name='is_header_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_header_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100, verbose_name='name')),
        ),
    ]
