# Generated by Django 4.1.2 on 2023-06-06 15:39

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('education', '0017_article_is_header_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendar',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cal_name', models.CharField(max_length=100, verbose_name='google calendar ID')),
                ('cal_credential_path', models.CharField(blank=True, default='credentials.json', max_length=255, verbose_name='google calendar credentials path')),
                ('is_default', models.BooleanField(default=False)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': 'google calendar',
                'verbose_name_plural': 'google calendars',
            },
        ),
        migrations.CreateModel(
            name='GoogleCalendarDetail',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cal_year', models.PositiveIntegerField(blank=True, default=2023, editable=False)),
                ('cal_month', models.PositiveIntegerField(blank=True, default=2023, editable=False)),
                ('cal_json', jsonfield.fields.JSONField(blank=True, null=True)),
                ('google_calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.googlecalendar', verbose_name='google calendar')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': 'google calendar detail',
                'verbose_name_plural': 'google calendars detail',
            },
        ),
    ]
