# Generated by Django 4.1.2 on 2023-06-17 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0021_alter_googlecalendar_cal_credential_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='googlecalendar',
            old_name='cal_credential_path',
            new_name='file_path_doc',
        ),
    ]
