# Generated by Django 4.1.2 on 2023-06-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0022_rename_cal_credential_path_googlecalendar_file_path_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='photogallery',
            name='is_header_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='order_item',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
